[tools]
cue = "latest"

[env]
CUE_REGISTRY="ghcr.io/repsejnworb"

[tasks.init]
description = "Initialize CUE module for this repo and fetch repo-forge templates (idempotent)"
depends     = ["init:module"]

[tasks."init:module"]
description = "Create cue.mod if missing, add templates module, tidy"
run = [
  "test -d cue.mod || cue mod init --source=git \"github.com/repsejnworb/${PWD##*/}\"@v0",
  "cue mod get github.com/repsejnworb/repoforger@v0",
  "cue mod tidy"
]